export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILED = "GET_ITEMS_FAILED";

export const ADD_FILLING = "ADD_ITEM";
export const DELETE_FILLING = "DELETE_FILLING";
export const REMOVE_FILLING = "REMOVE_FILLING";

export const CHANGE_BUN = "CHANGE_BUN";

export const OPEN_INFO_POPUP = "OPEN_INFO_POPUP";
export const SEND_ORDER_REQUEST = "SEND_ORDER_REQUEST";
export const SEND_ORDER_SUCCESS = "SEND_ORDER_SUCCESS";
export const SEND_ORDER_FAILED = "SEND_ORDER_FAILED";

export const EDIT_ORDER_DND = "EDIT_ORDER_DND";
