export const WS_CONNECTION_USER_START = "WS_CONNECTION_USER_START";
export const WS_CONNECTION_USER_SUCCESS = "WS_CONNECTION_USER_SUCCESS";
export const WS_CONNECTION_USER_ERROR = "WS_CONNECTION_USER_ERROR";
export const WS_CONNECTION_USER_CLOSED = "WS_CONNECTION_USER_CLOSED";
export const WS_GET_USER_ORDERS = "WS_GET_USER_ORDERS";
export const WS_SEND_USER_MESSAGE = "WS_SEND_USER_MESSAGE";
